import 'package:aniliberty_multiplatform/src/core/core.dart';
import 'package:aniliberty_multiplatform/src/datasource_v2/datasource_v2.dart';
import 'package:aniliberty_multiplatform/src/features/franchises/widget/scope/franchises_scope.dart';
import 'package:flutter/material.dart';

// generated by cursor
class FranchiseCardItem extends StatelessWidget {
  final AnimeFranchiseModel animeFranchise;

  const FranchiseCardItem({required this.animeFranchise, super.key});

  @override
  Widget build(BuildContext context) => Card(
    margin: EdgeInsets.zero,
    elevation: 4,
    shadowColor: Colors.black.withValues(alpha: 0.1),
    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
    child: InkWell(
      onTap: () => _onTap(context),
      borderRadius: BorderRadius.circular(16),
      child: Container(
        height: 200,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(16),
          gradient: LinearGradient(
            begin: Alignment.topLeft,
            end: Alignment.bottomRight,
            colors: [
              Theme.of(context).colorScheme.surface,
              Theme.of(context).colorScheme.surface.withValues(alpha: 0.95),
            ],
          ),
        ),
        child: Stack(
          children: [
            // Фоновое изображение с размытием
            Positioned.fill(
              child: ClipRRect(
                borderRadius: BorderRadius.circular(16),
                child: _BackgroundImage(animeFranchise.image),
              ),
            ),
            // Градиентный оверлей
            Positioned.fill(
              child: Container(
                decoration: BoxDecoration(
                  borderRadius: BorderRadius.circular(16),
                  gradient: LinearGradient(
                    begin: Alignment.topCenter,
                    end: Alignment.bottomCenter,
                    colors: [
                      Colors.transparent,
                      Colors.black.withValues(alpha: 0.3),
                      Colors.black.withValues(alpha: 0.7),
                    ],
                    stops: const [0.0, 0.5, 1.0],
                  ),
                ),
              ),
            ),
            // Основной контент
            Positioned.fill(
              child: Padding(
                padding: const EdgeInsets.all(20),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    // Верхняя секция с рейтингом
                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Expanded(child: _TitleSection(animeFranchise)),
                        if (animeFranchise.rating != null)
                          _RatingBadge(animeFranchise.rating!),
                      ],
                    ),
                    const Spacer(),
                    // Нижняя секция с информацией
                    _InfoSection(animeFranchise),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    ),
  );

  void _onTap(BuildContext context) {
    final navigator = FranchisesScope.navigationInteractorOf(
      context,
      listen: false,
    );

    return navigator.openFranchiseById(animeFranchise.id);
  }
}

class _BackgroundImage extends StatelessWidget {
  final PosterPreviewModel poster;

  const _BackgroundImage(this.poster);

  @override
  Widget build(BuildContext context) => Stack(
    fit: StackFit.expand,
    children: [
      StorageNetworkImage(
        src: poster.optimized.src,
        thumbnail: poster.optimized.thumbnail,
      ),
      // Размытый слой
      DecoratedBox(
        decoration: BoxDecoration(color: Colors.black.withValues(alpha: 0.4)),
      ),
    ],
  );
}

class _TitleSection extends StatelessWidget {
  final AnimeFranchiseModel animeFranchise;

  const _TitleSection(this.animeFranchise);

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final textTheme = theme.textTheme;

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          animeFranchise.name,
          style: textTheme.titleLarge?.copyWith(
            color: Colors.white,
            fontWeight: FontWeight.w700,
            height: 1.2,
            shadows: [
              Shadow(
                color: Colors.black.withValues(alpha: 0.5),
                offset: const Offset(0, 1),
                blurRadius: 3,
              ),
            ],
          ),
          maxLines: 2,
          overflow: TextOverflow.ellipsis,
        ),
        if (animeFranchise.nameEnglish.isNotEmpty) ...[
          const SizedBox(height: 4),
          Text(
            animeFranchise.nameEnglish,
            style: textTheme.bodyMedium?.copyWith(
              color: Colors.white.withValues(alpha: 0.8),
              fontWeight: FontWeight.w400,
              shadows: [
                Shadow(
                  color: Colors.black.withValues(alpha: 0.3),
                  offset: const Offset(0, 1),
                  blurRadius: 2,
                ),
              ],
            ),
            maxLines: 1,
            overflow: TextOverflow.ellipsis,
          ),
        ],
      ],
    );
  }
}

class _RatingBadge extends StatelessWidget {
  final double rating;

  const _RatingBadge(this.rating);

  @override
  Widget build(BuildContext context) => Container(
    padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
    decoration: BoxDecoration(
      color: _getRatingColor(rating).withValues(alpha: 0.9),
      borderRadius: BorderRadius.circular(20),
      boxShadow: [
        BoxShadow(
          color: Colors.black.withValues(alpha: 0.2),
          offset: const Offset(0, 2),
          blurRadius: 4,
        ),
      ],
    ),
    child: Row(
      mainAxisSize: MainAxisSize.min,
      children: [
        const Icon(Icons.star, size: 16, color: Colors.white),
        const SizedBox(width: 4),
        Text(
          rating.toStringAsFixed(1),
          style: const TextStyle(
            color: Colors.white,
            fontWeight: FontWeight.w600,
            fontSize: 14,
          ),
        ),
      ],
    ),
  );

  Color _getRatingColor(double rating) {
    if (rating >= 8.5) return Colors.green;
    if (rating >= 7.5) return Colors.orange;
    if (rating >= 6.5) return Colors.yellow.shade700;
    return Colors.red;
  }
}

class _InfoSection extends StatelessWidget {
  final AnimeFranchiseModel animeFranchise;

  const _InfoSection(this.animeFranchise);

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        // Годы
        _InfoRow(
          icon: Icons.calendar_today,
          text: animeFranchise.yearsLabel,
          color: Colors.blue.shade300,
        ),
        const SizedBox(height: 8),
        // Сезоны и эпизоды
        _InfoRow(
          icon: Icons.tv,
          text: animeFranchise.totalReleaseAndEpisodesLabel,
          color: Colors.purple.shade300,
        ),
        const SizedBox(height: 8),
        // Длительность
        _InfoRow(
          icon: Icons.timer,
          text:
              animeFranchise.totalDuration ??
              '${(animeFranchise.totalDurationInSeconds / 3600).toStringAsFixed(1)} ч',
          color: Colors.green.shade300,
        ),
      ],
    );
  }
}

class _InfoRow extends StatelessWidget {
  final IconData icon;
  final String text;
  final Color color;

  const _InfoRow({required this.icon, required this.text, required this.color});

  @override
  Widget build(BuildContext context) => Row(
    children: [
      Container(
        padding: const EdgeInsets.all(4),
        decoration: BoxDecoration(
          color: color.withValues(alpha: 0.2),
          borderRadius: BorderRadius.circular(6),
        ),
        child: Icon(icon, size: 14, color: color),
      ),
      const SizedBox(width: 8),
      Expanded(
        child: Text(
          text,
          style: Theme.of(context).textTheme.bodySmall?.copyWith(
            color: Colors.white.withValues(alpha: 0.9),
            fontWeight: FontWeight.w500,
            shadows: [
              Shadow(
                color: Colors.black.withValues(alpha: 0.3),
                offset: const Offset(0, 1),
                blurRadius: 2,
              ),
            ],
          ),
          maxLines: 1,
          overflow: TextOverflow.ellipsis,
        ),
      ),
    ],
  );
}
